# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron:  "0 9 * * *"
  workflow_dispatch:
  push:
    branches: [main, gh-workflow]

name: webscraping-bancos-rd

jobs:
  run-workflow:
    runs-on: ubuntu-latest

    name: ${{ matrix.browser }} (${{ matrix.version }})

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
        version: [latest]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      
    services:
      selenium:
        image: selenium/standalone-${{ matrix.browser }}:${{ matrix.version }}
        ports:
          - 4444:4444
        volumes:
          - /dev/shm:/dev/shm
      test-server:
        image: juyeongkim/test-server

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.3.1
          use-public-rspm: true
          
      - name: Execute Script
        run: |
          Rscript "scripts/test-rselenium.R"

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Automatic update with GitHub actions" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          