on:
  schedule:
    - cron:  "0 20 * * *"
  workflow_dispatch:

name: webscraping-supercasas

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Execute Script
        run: |
          Rscript "action.R"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Automatic update with GitHub actions" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
