on:
  schedule:
    - cron:  "0 20 * * *"
  workflow_dispatch:

name: webscraping-tc

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    name: ${{ matrix.browser }} (${{ matrix.version }})

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
        version: [2.53.1, 3.141.59, latest]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    services:
      selenium:
        image: selenium/standalone-${{ matrix.browser }}:${{ matrix.version }}
        ports:
          - 4444:4444
        volumes:
          - /dev/shm:/dev/shm
      test-server:
        image: juyeongkim/test-server
jobs:
  run-r-script:
    runs-on: ubuntu-latest

    name: ${{ matrix.browser }} (${{ matrix.version }})

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
        version: [2.53.1, 3.141.59, latest]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    services:
      selenium:
        image: selenium/standalone-${{ matrix.browser }}:${{ matrix.version }}
        ports:
          - 4444:4444
        volumes:
          - /dev/shm:/dev/shm
      test-server:
        image: juyeongkim/test-server        
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Execute Script
        run: |
          Rscript "action.R"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Automatic update with GitHub actions" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
