name: Get Banreservas Exchange Rates

on:
  push:
    branches: [ main, wb-br ]
  pull_request:
    branches: [ main, wb-br ]
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-rscript:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'
    
    - name: Install required system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("RSelenium", "pagedown", "rvest", "tidyverse", "wdman"), repos = "https://cloud.r-project.org")'
        
    - name: Setup Chrome and ChromeDriver
      run: |
        # Update the apt key handling (newer approach)
        sudo apt-get update
        sudo apt-get install -y wget
        
        # Install Chrome using a more reliable method
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
        
        # Verify Chrome installation
        google-chrome --version
        
        # Install ChromeDriver using webdriver package in R
        Rscript -e 'wdman::chrome()'
    
    - name: Run exchange rates script
      run: |
        Rscript scripts/example-banreservas.R
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: exchange-rates
        path: banreservas_rates_*.csv
        retention-days: 90